<?php
// this file is generated by 
// http://localhost:3000/api/generate_config_files

// TODO: REMOVE supported_languages IN future


return [
	
	'supported_languages' => [
'en_EN',
'es_ES',
'ru_RU',
'fr_FR',
'de_DE',
'pl_PL',

	],

	'dict_tables' => [
'en_EN' => 'dictionary_en',
'es_ES' => 'dictionary_es',
'ru_RU' => 'dictionary_ru',
'fr_FR' => 'dictionary_fr',
'de_DE' => 'dictionary_de',
'pl_PL' => 'dictionary_pl',

	],

	'languages_id' => [
'en_EN' => '1',
'es_ES' => '2',
'ru_RU' => '3',
'fr_FR' => '4',
'de_DE' => '5',
'pl_PL' => '6',

		]

];